# Generated by Django 6.0.6 on 2026-06-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='stage_type',
            field=models.CharField(choices=[('entry', 'Entry'), ('middle', 'Middle'), ('won', 'Won'), ('lost', 'Lost')], default='middle', max_length=20),
        ),
    ]
