# Generated by Django 6.0.6 on 2026-06-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_product_lead_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
    ]
