# Generated by Django 6.0.6 on 2026-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead_photo_leadattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
