# Generated by Django 6.0.6 on 2026-06-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_customerprofile_color_leadsource_color_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='crm.product'),
        ),
    ]
