# Generated by Django 6.0.6 on 2026-06-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_user_otp_code_user_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
