# Generated by Django 6.0.6 on 2026-07-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_loginactivity_logged_out_at_campaign_campaignview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginactivity',
            name='logged_out_at',
        ),
    ]
