# Generated by Django 6.0.6 on 2026-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_loginactivity_logged_out_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='message_type_other',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=10),
        ),
    ]
