# Generated by Django 6.0.6 on 2026-07-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_drop_orphan_task_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='leads_multi', to='crm.product'),
        ),
    ]
