# Generated by Django 6.0.6 on 2026-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_add_lead_products_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['deleted_at', '-created_at'], name='crm_lead_deleted_138e96_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['deleted_at', 'stage', '-created_at'], name='crm_lead_deleted_6c2020_idx'),
        ),
    ]
